language: objective-c
osx_image: xcode8
before_install:
- gem install xcpretty
- carthage bootstrap --platform ios
script:
- set -o pipefail
- export IOS_SIMULATOR_UDID=`instruments -s devices | grep "iPhone 6 (10.0" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
- echo $IOS_SIMULATOR_UDID
- open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID
- xcodebuild -scheme DronePan -sdk iphonesimulator10.0 -destination "platform=iOS Simulator,name=iPhone 6,OS=10.0" -enableCodeCoverage YES test | xcpretty
after_success:
- bash <(curl -s https://codecov.io/bash) -J DronePan
notifications:
  webhooks:
    urls:
      secure: UmkkU540M0ckQcHRG3iBWBt2lZW33zd7zC3zRt3WoK/N3jo0qWJKBKFuVIf3nUt6Br79SwbznYHtsHb7YuXg4UCVs3H+dilxZu/q+/c9jEYnVY7ek/4+MILmRMjq2ylc8y7pO8EdyHj5WcgWngYNdJyRtM4OTfJVFToDcPR9x5u2xP2PO5bSAANDmMuhUTu3PzYTXrSjnDtSUeSt5XwIhK1boMXzgUYHmaUFLZyBDgQw43VVv36h+YS1CMVTpyyy5pioNnPesFBnk6QNUZAFUFil38Bi48OVPrwLlE5JiYX4xqxW3EjY7lHTAr88ay6H5+Hw21QAWCqlBMLaGqxYvRKMWpwLoFi14lUKud2HKqxrduWtNhZf/AIY3Psc0wJculCdlgpTiSTJyMAHpiidUib2qkLOVEe89kUPN8Tv57coUx/15Zwn11+1lZYCgo4CfMFCr5M2sOxZ/aVnFkulXOMStLZ1bF6Hk2ix30jI27qL2H5alThsdo13jhLWnKpVr2qoXJjRTszA79wBdBnDQS5tn0vC91AcnvMeSTG3yHAx57Iu1EihW8Dka4selpEQ476RI+r2VBKhU6sOYmT3BdIeJcFX3oZ/wTXJ85ikkMdCiAHuG6Exn8101gKDrGekFaeT5g3FyAYpLBbdHZv653CwglSrjVvuPSNOFRzVBIE=
    on_success: change
    on_failure: always
    on_start: never
env:
  global:
    secure: dmY+wVyhHp0B/uKKDqwsf1RTPkeRHh3lCeBUxHidvq0Y/vI9DqJ07EtcPoEfdWjro/ljhD3dnfuojLsT4ReD2b0fvYG4OI9IK3K0HLauwm5sufCXn0qc8rCis3EhaG/qqV9xNYVf3/MEYwjBaFMMPmGvW/gARW/9hkI19g13AGPznixUVRyLVwifLfB1d+5mN+dXot3N0pyhQniHy2xh3XFbyJmYeOygOtY12S1kcuQ1JgaLbV1zCZBE3kIIr0BJvgC+PsJfZLxeRMly1xuiuEEMLnSS+VItywvM+zCf4RtmdDutvZYcwKzqSvJEPydV9j11AxlPw5YsTbv+E6GdfwG0Ev/vTAXe2gpDJQrXnK706jmmEAMR35NDbQ3lY9GRkaCpT0XVubchrGR/eywb/nL7hW3S8hQzUeMbFaBs3ZHs/EC9+wlm1L9Ov3/TthtqZTbNEw0TtCO4M5sscYoEtUjhmwvAFArXFK4RZP7QnRrDZBqXxmSECNUue6QQ/tw4hC1pBqdaOM1BwlEI3bZll3hpuXiTKktMwreq//syN2v2qRmnkoGSg+iPXZjVNwlAyDRyeeiHgzI3CjOwL9Wa2EsH4uH5noyIpNjvjUSdoxtO60eiYKr6saL0X1zW9/xVsx+H3lerhWZ9k77zVZPVfJnhqQnhFw/09F5vL0Q6QUg=
